export const user_initialState = [
  {
    id: 1,
    firstName: 'firstName1',
    lastName: 'lastName1',
    internationalName: 'internationalName1',
    email: 'test@test.com',
    address: 'address1',
    city: 'City1',
    country: 'Country1',
    postalCode: 'PostalCode1',
    title: 'title1',
    companyPhone: 'companyPhone1',
    companyCode: 'companyCode1',
    buissnessUnit: 'buisnessUnit1',
    costCenter: 'costCenter1',
    managementGroup: 'managementGroup1',
  },
  {
    id: 2,
    firstName: 'firstName2',
    lastName: 'lastName2',
    internationalName: 'internationalName2',
    email: 'test@test.com',
    address: 'address2',
    city: 'City2',
    country: 'Country2',
    postalCode: 'PostalCode2',
    title: 'title2',
    companyPhone: 'companyPhone2',
    companyCode: 'companyCode2',
    buissnessUnit: 'buisnessUnit2',
    costCenter: 'costCenter2',
    managementGroup: 'managementGroup2',
  },
]
