export const CREATE_BEST_PRACTICE = "CREATE_BEST_PRACTICE";
export const RETRIEVE_BEST_PRACTICES = "RETRIEVE_BEST_PRACTICE";
export const UPDATE_BEST_PRACTICE = "UPDATE_BEST_PRACTICE";
export const DELETE_BEST_PRACTICE = "DELETE_BEST_PRACTICE";
export const RETRIEVE_SINGLE_BEST_PRACTICE = "RETRIEVE_SINGLE_BEST_PRACTICE";