//CareMember  - Best Practice Management Actions
export const CREATE_BEST_PRACTICE = "CREATE_BEST_PRACTICE";
export const ADD_ATTACHMENT_TO_BEST_PRACTICE = "ADD_ATTACHMENT_TO_BEST_PRACTICE" //NB: A redux action might not be needed for this..needs more discussion
export const DELETE_ATTACHMENT_FROM_BEST_PRACTICE = "DELETE_ATTACHMENT_FROM_BEST_PRACTICE"
export const DELETE_BEST_PRACTICE = "DELETE_BEST_PRACTICE";
export const SEARCH_BEST_PRACTICE = "SEARCH_BEST_PRACTICE";
export const RATE_BEST_PRACTICE = "RATE_BEST_PRACTICE";
export const TAG_BEST_PRACTICE = "TAG_BEST_PRACTICE";
export const SHARE_BEST_PRACTICE = "SHARE_BEST_PRACTICE";