//Care Captain - Training Management Actions
export const ASSIGN_CARE_USER_TO_TRAININGS = "ASSIGN_CARE_USER_TO_TRAININGS";
export const CREATE_TRAINING = "CREATE_TRAINING";
export const EDIT_TRAINING = "EDIT_TRAINING"
export const DEACTIVATE_TRAINING  = "DEACTIVATE_TRAINING";
export const CREATE_TRAINING_TRAIL = "CREATE_TRAINING_TRAIL";
export const ADD_TRAINING_TO_TRAIL = "ADD_TRAINING_TO_TRAIL";
export const REMOVE_TRAINING_FROM_TRAIL = "REMOVE_TRAINING_FROM_TRAIL";