export const ONBOARD_EMPLOYEES = "ONBOARD_EMPLOYEES";
export const OFFBOARD_CARE_USER = "OFFBOARD_CARE_USER";
export const RESIGN_CARE_USER = "RESIGN_CARE_USER";
export const LOGIN_CARE_USER = "LOGIN_CARE_USER";
export const LOGOUT_CARE_USER = "LOGOUT_CARE_USER";
export const RETRIEVE_EMPLOYEES = "RETRIEVE_EMPLOYEES";
export const RETRIEVE_CARE_MEMBERS = "RETRIEVE_CARE_MEMBERS";
export const SEARCH_CARE_USER = "SEARCH_CARE_USER";